<?php
/**
 * RenderApi
 * PHP version 5
 *
 * @category Class
 * @package  Shotstack
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

namespace Shotstack\Api;

use \Shotstack\Configuration;
use \Shotstack\ApiClient;
use \Shotstack\ApiException;
use \Shotstack\ObjectSerializer;

/**
 * RenderApi Class Doc Comment
 *
 * @category Class
 * @package  Shotstack
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RenderApi
{

    /**
     * API Client
     * @var \Shotstack\ApiClient instance of the ApiClient
     */
    protected $apiClient;
  
    /**
     * Constructor
     * @param \Shotstack\ApiClient|null $apiClient The api client to use
     */
    function __construct($apiClient = null)
    {
        if ($apiClient == null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('http://api.shotstack.io/v1');
        }
  
        $this->apiClient = $apiClient;
    }
  
    /**
     * Get API client
     * @return \Shotstack\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }
  
    /**
     * Set the API client
     * @param \Shotstack\ApiClient $apiClient set the API client
     * @return RenderApi
     */
    public function setApiClient(ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }
  
    
    /**
     * postRender
     *
     * 
     *
     * @param \Shotstack\Model\Edit $edit Edit (required)
     * @return \Shotstack\Model\QueuedResponse
     * @throws \Shotstack\ApiException on non-2xx response
     */
    public function postRender($edit)
    {
        list($response, $statusCode, $httpHeader) = $this->postRenderWithHttpInfo ($edit);
        return $response; 
    }


    /**
     * postRenderWithHttpInfo
     *
     * 
     *
     * @param \Shotstack\Model\Edit $edit Edit (required)
     * @return Array of \Shotstack\Model\QueuedResponse, HTTP status code, HTTP response headers (array of strings)
     * @throws \Shotstack\ApiException on non-2xx response
     */
    public function postRenderWithHttpInfo($edit)
    {
        
        // verify the required parameter 'edit' is set
        if ($edit === null) {
            throw new \InvalidArgumentException('Missing the required parameter $edit when calling postRender');
        }
  
        // parse inputs
        $resourcePath = "/render";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($edit)) {
            $_tempBody = $edit;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('x-api-key');
        if (strlen($apiKey) !== 0) {
            $headerParams['x-api-key'] = $apiKey;
        }
        
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'POST',
                $queryParams, $httpBody,
                $headerParams, '\Shotstack\Model\QueuedResponse'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Shotstack\ObjectSerializer::deserialize($response, '\Shotstack\Model\QueuedResponse', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Shotstack\ObjectSerializer::deserialize($e->getResponseBody(), '\Shotstack\Model\QueuedResponse', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
}
